### ISSUE TITLE
Mixed messages on code reuse

### ISSUE THREAD

**Issue by pkgw** [ska-sa/katportalclient#28]
The headers of the source files in this repository state:

```
# Copyright @ 2013 SKA SA. All rights reserved.                               #
#                                                                             #
# THIS SOFTWARE MAY NOT BE COPIED OR DISTRIBUTED IN ANY FORM WITHOUT THE      #
# WRITTEN PERMISSION OF SKA SA.                                               #
```

This implies that they should never have been uploaded to GitHub in the first place. If this code is actually meant to be public, it should be distributed under some license that allows reuse.

**Comment by martinslabber** [comment]
Thanks @pkgw 
The licence is BSD and the files should state that, the same as used in https://github.com/ska-sa/katcp-python.
We will update the repo to reflect the correct licence.
Thanks for pointing this out.
Regards,

**Comment by ajoubertza** [comment]
Hi @pkgw. This has been fixed.
