### ISSUE TITLE
Feature to return latest sensor value

### ISSUE THREAD

**Issue by ewanbarr** [ska-sa/katportalclient#33]
As a quality-of-life improvement when using the code it would be good to have a feature that allows you to only retrieve the last reading of a sensor. Currently it is only possible to retrieve sensor histories and this leads to unwanted behaviours. For example if I do not _a priori_ know of often a sensor is updated, I must guess the epoch over which I want histories returned. For rapidly updating sensors I may then get a slew of returned values while for sensors that are seldom updated I may not get any value. 

The prototype for such a method would be something like:

```python
class KATPortalClient(object):
    ...
    @tornado.gen.coroutine
    def sensor_value(self, sensor_name, include_value_ts=False, timeout_sec=300):
    """Return the most recent measurement for a sensor.
    ...
    """
```

**Comment by ajoubertza** [comment]
This is a good suggestion - we will add it.  Thanks for detailed explanation.

**Comment by SKAJohanVenter** [comment]
@ewanbarr Please have a look at https://github.com/ska-sa/katportalclient/pull/34
